version: 0.2

phases:
  install:
    runtime-version:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo repo name is $IMAGE_REPO_NAME
      - echo Building the Docker image...          
      - docker build -t docker-image-repo .
      - docker tag docker-image-repo:latest 134867112207.dkr.ecr.us-east-1.amazonaws.com/docker-image-repo:latest      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 134867112207.dkr.ecr.us-east-1.amazonaws.com/docker-image-repo:latest